USE ROLE SECURITYADMIN;

-- Service role for dbt, no UI access
CREATE ROLE IF NOT EXISTS DBT_DEV_ROLE;

-- Separate read-only role for BI. Power BI gets SELECT on marts only
CREATE ROLE IF NOT EXISTS BI_READER_ROLE;

-- Create service account. DBT_USER cannot log into Snowflake
CREATE USER IF NOT EXISTS DBT_USER
    TYPE = SERVICE
    DEFAULT_ROLE = DBT_DEV_ROLE
    DEFAULT_WAREHOUSE = DBT_WH_XS
    COMMENT = 'Service account for dbt Core';

ALTER USER DBT_USER SET RSA_PUBLIC_KEY = 'PASTE_THE_PUBLIC_KEY';

GRANT ROLE DBT_DEV_ROLE TO USER DBT_USER;
GRANT ROLE DBT_DEV_ROLE TO ROLE SYSADMIN;
GRANT ROLE BI_READER_ROLE TO ROLE SYSADMIN;

-- Grant BI_READER so Power BI can connect using it
GRANT ROLE BI_READER_ROLE TO USER <USERNAME>;

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS DBT_WH_XS
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60  -- suspend after 60s idle
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Transformation compute for Olist analytics project.';

CREATE DATABASE IF NOT EXISTS OLIST_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS OLIST_ANALYTICS.RAW;
CREATE SCHEMA IF NOT EXISTS OLIST_ANALYTICS.ANALYTICS;

-- dbt: create and usage privileges within project database
GRANT USAGE ON WAREHOUSE DBT_WH_XS TO ROLE DBT_DEV_ROLE;
GRANT ALL ON DATABASE OLIST_ANALYTICS TO ROLE DBT_DEV_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE OLIST_ANALYTICS TO ROLE DBT_DEV_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE OLIST_ANALYTICS TO ROLE DBT_DEV_ROLE;

-- BI: read-only, marts schema only, no raw access
GRANT USAGE ON WAREHOUSE DBT_WH_XS TO ROLE BI_READER_ROLE;
GRANT USAGE ON DATABASE OLIST_ANALYTICS TO ROLE BI_READER_ROLE;
GRANT USAGE ON SCHEMA OLIST_ANALYTICS.ANALYTICS TO ROLE BI_READER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA OLIST_ANALYTICS.ANALYTICS TO ROLE BI_READER_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA OLIST_ANALYTICS.ANALYTICS TO ROLE BI_READER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OLIST_ANALYTICS.ANALYTICS TO ROLE BI_READER_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA OLIST_ANALYTICS.ANALYTICS TO ROLE BI_READER_ROLE;

-- Suspends the warehouse at 100% of quota
USE ROLE ACCOUNTADMIN;
CREATE RESOURCE MONITOR IF NOT EXISTS OLIST_PORTFOLIO_MONITOR
    WITH CREDIT_QUOTA = 25
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE DBT_WH_XS SET RESOURCE_MONITOR = OLIST_PORTFOLIO_MONITOR;